version: '3.8'
services:
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      # these variables are also present in .env; listed here for clarity
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      EDGE_SECRET: ${EDGE_SECRET}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app   # Dev only

  frontend:
    build: ./frontend
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:8000"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app   # Dev only

  edge-sim:
    build: ./edge
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      BACKEND_URL: "http://backend:8000"
      EDGE_SECRET: ${EDGE_SECRET}
    ports:
      - "9000:9000"
    volumes:
      - ./edge:/app

volumes:
  db_data:
